version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "8090:8090"
    volumes:
      - ./frontend/:/app
    tty: true
  backend:
    build: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app
    tty: true
